# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56649c0647dadb76ce99eeb2f14173859a06ba90eff6f6347a3b186388e970d8877bdcf03a16b6531639b6ade3e97733df4be6b3d8a0697ddac05974448ac162

test:
  secret_key_base: f77353b49e2f41a23c58ac7d28cfa15092de8ad862a17407f2bb8f4312fb56ef38d17356cefb794a48d7a6d145e77c044a36a31f2867dfb1e56f43d5e6899d61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
